spring:
  datasource:
    driver-class-name : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/board?serverTimezone=Asia/Seoul
    username : ahn
    password : 1234
    
  jpa:
    open-in-view : true
    hibernate:
      # ddl-auto - 프로젝트 실행 시 자동으로 DDL(create, drop, alter 등)을 자동으로 생성할 지 결정
      # 주로 create와 update를 사용
      ddl-auto : create
      # use-new-id-generate-mappings - JPA의 기본 넘버링 사용 여부
      use-new-id-generate-mappings : false
    # 프로젝트 실행 시 sql문을 로그로 노출
    show-sql : true
    properties:
      # sql을 포맷팅하여 로그로 정리된 sql을 노출함
      hibernate.format_sql : true